before_script:
    - export CI_APP_VOLUME=$CI_PROJECT_DIR
    - export COMPOSE_PROJECT_NAME=testpages
    - mv tests/docker-compose.ci.override.yml tests/docker-compose.override.yml
    - cd tests

stages:
  - test
  - cleanup

test:
    stage: test
    script:
        - set +e
        - sh test.sh; export TESTS_EXIT_CODE=$?
        - set -e
        - exit $TESTS_EXIT_CODE
    artifacts:
        paths:
          - tests/_output/

cleanup:
    stage: cleanup
    script:
        - docker-compose kill && docker-compose rm -fv
