before_script:
  - export BUILD_PREFIX=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export CI_APP_VOLUME=$CI_PROJECT_DIR
  - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}yii2pages
  - mv tests/docker-compose.ci.override.yml tests/docker-compose.override.yml
  - cd tests

stages:
  - test
  - cleanup

test:
  stage: test
  script:
    - set +e
    - docker-compose up -d
    - docker-compose run YII_ENV=test codecept run -c /app/vendor/dmstr/yii2-pages-module/codeception.yml
    - TESTS_EXIT_CODE=$?
    - set -e
    - exit $TESTS_EXIT_CODE
  artifacts:
    paths:
      - tests/_output/

cleanup:
  stage: cleanup
  script:
    - docker-compose kill && docker-compose rm -fv
  when: always
